### ISSUE TITLE
[EPIC] YYYY

### ISSUE THREAD

**Issue by owerfly** [owerfly/test2#6]
# GOAL 
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque vitae magna sed ligula consequat molestie convallis sed velit. Sed ut libero vitae metus luctus mollis ut in odio. 

# WHY
Donec porttitor vestibulum consectetur. Donec pretium tincidunt erat ut commodo. Aenean nisi nisi, placerat quis rhoncus eu, placerat nec sem. Maecenas eget faucibus felis, id aliquam mauris. Integer pharetra tellus sed dui efficitur accumsan. Praesent malesuada feugiat orci eget aliquet. 

# Valuable Issues 
### Must Have 
- [x]  #1  - [Must Have] - 3/2 - V1.7.9 - azerty azerty azerty azerty azerty azerty azerty  
- [ ]  #2 - [Nice Have]- 5/? - V? - azerty azerty azerty azerty azerty azerty azerty 
### Nice to Have 
- [x]  #1  - [Must Have] - 3/2 - V1.7.9 - azerty azerty azerty azerty azerty azerty azerty  
- [ ]  #2 - [Nice Have]- 5/? - V? - azerty azerty azerty azerty azerty azerty azerty 

## IMPROVEMENTS
- [x]  #3  - [Must Have] - 3/2 - V1.7.9 - azerty azerty azerty azerty azerty azerty azerty  
- [ ]  #4 - [Nice Have]- 5/? - V? - azerty azerty azerty azerty azerty azerty azerty 

# BUGS 
## CRITICAL BUGS 
- [x]  #22668 - ? - V1.7.7.4 - azerty azerty azerty azerty azerty azerty azerty  
- [ ]  #22658 - ? - V1.7.7.4 - azerty azerty azerty azerty azerty azerty azerty 

## MAJOR BUGS
- [x]  #22668 - ? - V1.7.7.4 - azerty azerty azerty azerty azerty azerty azerty  
- [ ]  #22658 - ? - V1.7.7.4 - azerty azerty azerty azerty azerty azerty azerty 

## MANOR BUGS
- [x]  #22668 - Estimation - [Version] - [Title] 
- [x]  #22658 - Estimation - [Version] - [Title]
